_default:
  just --list

console:
  docker-compose run --rm core rails c

test:
  docker-compose run -e RAILS_ENV=test --rm core rspec-all
  docker-compose run -e RAILS_ENV=test --rm core rails zeitwerk:check
  docker run -v "$(pwd)":/code presidentbeef/brakeman:v6.0.1 --color --skip-files=engines/admin/app/controllers/admin/application_controller.rb

dump:
  #!/usr/bin/env zsh
  source $HOME/.zshrc
  docker-compose down
  docker-compose up -d core-db
  iacli "core:load_dump[production,development]"
  docker-compose up -d

replicate:
  docker-compose run --rm core rails odoo:replication
