#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[default_session]
startup_command = "nvim ."
windows = ["zsh"]

[[session]]
name = "architecture"
path = "~/git/architecture"
startup_command = "journalctl --user -u traefik-ia.service -f"
windows = ["zsh"]

[[session]]
name = "core"
path = "~/git/architecture/apps/core"
windows = ["core-console", "zsh", "opencode"]

[[wildcard]]
pattern = "~/git/architecture/apps/*"
windows = ["zsh", "zsh", "opencode"]

[[window]]
name = "zsh"
startup_script = "ls"

[[window]]
name = "opencode"
startup_script = "opencode"

[[window]]
name = "core-console"
startup_script = "docker-compose run --rm core rails c"
