autoclip: false
autoimport: true
cliptimeout: 45
exportkeys: true
nocolor: false
nopager: false
notifications: true
parsing: true
path: /home/seims/.local/share/gopass/stores/root
safecontent: false
mounts:
    inaudito: /home/seims/git/passwords
