[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
opacity = 1
padding.x = 0
padding.y = 0
decorations = "None"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 11.0

[scrolling]
history = 100000

# https://gist.github.com/sainnhe/6432f83181c4520ea87b5211fed27950
[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"
