[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false

[settings.python]
compile = false

[settings.node]
compile = false

[tools]
node = "latest"
python = "latest"
ruby = "latest"
